version: 0.0
os: linux
files:
  - source: target/
    destination: /var/lib/tomcat/webapps/firstproject123-1.0-SNAPSHOT
permissions:
  - object: /var/lib/tomcat/webapps/firstproject123-1.0-SNAPSHOT
    pattern: "**"
    owner: tomcat8
    group: tomcat8


