version: 0.0
os: windows
files:
  - source: target/
    destination: C:\tomcat\webapps\
hooks:
  BeforeInstall:
    - location: BeforeInstall.ps1
      timeout: 900
  AfterInstall:
    - location: AfterInstall.ps1
      timeout: 900
  ApplicationStart:
    - location: ApplicationStart.ps1
      timeout: 900
