version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      
    commands:
      - echo "Installing Maven..."
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - echo "Building the application..."
      - mvn clean install
  build:
    commands:
      - echo "Creating WAR file..."
      - mvn package
  post_build:
    commands:
      - echo "Post build steps..."
      # Add any post-build steps here
artifacts:
  files:
    - target/*.war
    - before_install.sh
    - after_install.sh
    - application_start.sh
    - application_stop.sh
  discard-paths: yes
